### ISSUE TITLE
WS: Compile XMLParsing in OpenESB

### ISSUE THREAD

**Issue by smokhov** [smokhov/atsm#8]
@leihaotao -- need this project to also build in OpenESB and have its project files added; currently it is Eclipse-only

- https://github.com/smokhov/atsm/tree/master/examples/ws/XML/XMLParsing

**Comment by jashanj0tsingh** [comment]
<strike>Except the JAXB example rest of them are running as in the latest version of OpenESB. I will update it to the latest conventions soon.</strike>
The subdirectory can be imported as an eclipse project in itself to OpenESB using the inbuilt import project from eclipse functionality. 

Edit: All the default examples are running. No updates are required as such for now.

**Comment by smokhov** [comment]
PR #11 sufficiently covered this.
